### ISSUE TITLE
crashing immediately after spawn

### ISSUE THREAD

**Issue by tzcrawford** [Plagman/gamescope#192]
After some system update, gamescope immediately crashes after spawning, regardless of which game I am trying to run.

I have listed a log below of the stdout and stderr from during one of these crashes while launching a game/application. This in particular was produced with `gamescope -w 640 -h 480 -W 640 -h 480 -- gedit 2>&1 | tee logfile.txt`. 

I think this must be the important line? 
```
gamescope: ../gamescope-3.7.1/src/steamcompmgr.cpp:616: bool import_commit(wlr_buffer*, wlr_dmabuf_attributes*, commit_t&): Assertion commit.vulkanTex != 0 failed.
``` 
A vulkan API problem??

```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
00:00:00.000 [INFO] [backend/headless/backend.c:129] Creating headless backend
00:00:00.026 [INFO] [render/egl.c:297] Using EGL 1.5
00:00:00.026 [INFO] [render/egl.c:298] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
00:00:00.026 [INFO] [render/egl.c:299] Supported EGL display extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image_base EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display
00:00:00.026 [INFO] [render/egl.c:300] EGL vendor: Mesa Project
00:00:00.026 [DEBUG] [render/egl.c:175] Supported dmabuf buffer formats: AB4H XB4H AR30 XR30 AB30 XB30 AR24 AB24 XR24 XB24 AR15 RG16 R8   R16  GR88 GR32 YUV9 YU11 YU12 YU16 YU24 YVU9 YV11 YV12 YV16 YV24 NV12 P010 P012 P016 NV16 AYUV XYUV YUYV UYVY
00:00:00.028 [INFO] [render/gles2/renderer.c:674] Using OpenGL ES 3.2 Mesa 21.1.0
00:00:00.028 [INFO] [render/gles2/renderer.c:675] GL vendor: AMD
00:00:00.028 [INFO] [render/gles2/renderer.c:676] GL renderer: Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.12.1-arch1-1, LLVM 11.1.0)
00:00:00.028 [INFO] [render/gles2/renderer.c:677] Supported GLES2 extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_AMD_performance_monitor GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_NV_conditional_render GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_OES_viewport_array GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_robustness GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_group_vote GL_EXT_shader_implicit_conversions GL_EXT_shader_integer_mix GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_ANDROID_extension_pack_es31a GL_EXT_base_instance GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_copy_image GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_gpu_shader5 GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_render_snorm GL_EXT_shader_io_blocks GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_norm16 GL_EXT_texture_view GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_NV_image_formats GL_OES_copy_image GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_gpu_shader5 GL_OES_primitive_bounding_box GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_texture_view GL_EXT_blend_func_extended GL_EXT_buffer_storage GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_shader_samples_identical GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_OES_EGL_image_external_essl3 GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_shader_image_atomic GL_EXT_clip_cull_distance GL_EXT_disjoint_timer_query GL_EXT_texture_compression_s3tc_srgb GL_EXT_window_rectangles GL_MESA_shader_integer_functions GL_EXT_clip_control GL_EXT_color_buffer_half_float GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_texture_compression_bptc GL_KHR_parallel_shader_compile GL_NV_alpha_to_coverage_dither_control GL_AMD_framebuffer_multisample_advanced GL_EXT_EGL_image_storage GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_demote_to_helper_invocation GL_EXT_depth_clamp GL_EXT_texture_query_lod
00:00:00.040 [ERROR] [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X1: Address already in use
00:00:00.040 [DEBUG] [GLES2] Shader Stats: SGPRS: 8 VGPRS: 28 Code Size: 44 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.042 [INFO] [wayland] unable to lock lockfile /run/user/1000/gamescope-0.lock, maybe another compositor is running
00:00:00.042 [INFO] [../gamescope-3.7.1/src/wlserver.cpp:505] Running compositor on wayland display 'gamescope-1'
00:00:00.042 [INFO] [backend/headless/backend.c:21] Starting headless backend
00:00:00.043 [INFO] [xwayland/server.c:92] WAYLAND_SOCKET=19 Xwayland :2 -rootless -terminate -listen 17 -listen 16 -wm -1
00:00:00.046 [DEBUG] [GLES2] Shader Stats: SGPRS: 8 VGPRS: 28 Code Size: 104 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.047 [DEBUG] [GLES2] Shader Stats: SGPRS: 16 VGPRS: 8 Code Size: 144 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.048 [DEBUG] [GLES2] Shader Stats: SGPRS: 16 VGPRS: 12 Code Size: 180 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
(WW) Option "-listen" for file descriptors is deprecated
Please use "-listenfd" instead.
(WW) Option "-listen" for file descriptors is deprecated
Please use "-listenfd" instead.
00:00:00.050 [DEBUG] [GLES2] Shader Stats: SGPRS: 24 VGPRS: 8 Code Size: 164 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.050 [DEBUG] [GLES2] Shader Stats: SGPRS: 24 VGPRS: 28 Code Size: 116 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.051 [DEBUG] [GLES2] Shader Stats: SGPRS: 24 VGPRS: 28 Code Size: 120 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.051 [DEBUG] [GLES2] Shader Stats: SGPRS: 8 VGPRS: 28 Code Size: 48 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.052 [DEBUG] [GLES2] Shader Stats: SGPRS: 24 VGPRS: 28 Code Size: 116 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.052 [DEBUG] [GLES2] Shader Stats: SGPRS: 24 VGPRS: 8 Code Size: 204 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
glamor: No eglstream capable devices found
00:00:00.193 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x5566b2efecd0 (res 0x5566b28f3200)
00:00:00.193 [DEBUG] [xwayland/server.c:343] sent SIGUSR1 to process 13983
00:00:00.194 [DEBUG] [xwayland/server.c:237] Xserver is ready
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
Unhandled NET_WM_STATE property change: _NET_WM_STATE_HIDDEN
00:00:00.478 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x5566b2f656f0 (res 0x5566b2f627a0)
Unhandled client message: _NET_STARTUP_INFO_BEGIN
Unhandled client message: _NET_STARTUP_INFO
Unhandled client message: _NET_STARTUP_INFO
00:00:00.498 [DEBUG] [GLES2] Shader Stats: SGPRS: 8 VGPRS: 28 Code Size: 20 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.501 [DEBUG] [GLES2] Shader Stats: SGPRS: 16 VGPRS: 8 Code Size: 84 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
gamescope: ../gamescope-3.7.1/src/steamcompmgr.cpp:616: bool import_commit(wlr_buffer*, wlr_dmabuf_attributes*, commit_t&): Assertion `commit.vulkanTex != 0' failed.
(EE) failed to read Wayland events: Connection reset by peer
```
This system is an Arch Linux install.
Linux 5.12.1, mesa 21.1.0-1
I'm using only Xorg, not Wayland.

**Comment by MGThePro** [comment]
I'm having the same issue, with an rx 580, and on plasma wayland and gamescope 3.8.4

**Comment by emersion** [comment]
Can you collect logs with `WAYLAND_DEBUG=server`?

**Comment by tzcrawford** [comment]
> Can you collect logs with `WAYLAND_DEBUG=server`?

This is what happens when I run:
`WAYLAND_DEBUG=server gamescope -w 640 -h 480 -W 640 -h 480 -- gedit 2>&1 | tee logfile.txt`

[logfile.txt](https://github.com/Plagman/gamescope/files/6742550/logfile.txt)

There's a couple of gedit errors on the last couple of lines for whatever reason.

**Comment by MGThePro** [comment]
For completeness, here's a log from me running `WAYLAND_DEBUG=server gamescope -- vkcube`
[logfile.txt](https://github.com/Plagman/gamescope/files/6800083/logfile.txt)

**Comment by Eoin-ONeill-Yokai** [comment]
I'm having this issue as well.

<details><summary>WAYLAND_DEBUG=server Log (Click Here!)</summary>

```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
Vulkan does not support DRM format modifiers
Supported DRM formats for sampling usage: 0x34325258, 0x34325241, 0x3231564E
00:00:00.000 [backend/headless/backend.c:202] Creating headless backend
00:00:00.000 [backend/headless/backend.c:179] Opening DRM render node '/dev/dri/renderD128'
00:00:00.003 [render/gbm_allocator.c:179] Created GBM allocator with backend drm
00:00:00.007 [render/egl.c:316] Using EGL 1.5
00:00:00.007 [render/egl.c:317] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
00:00:00.007 [render/egl.c:318] Supported EGL display extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display
00:00:00.007 [render/egl.c:320] Supported EGL device extensions: EGL_EXT_device_drm EGL_EXT_device_drm_render_node
00:00:00.007 [render/egl.c:322] EGL vendor: Mesa Project
00:00:00.007 [render/egl.c:149] Supported DMA-BUF formats: AB4H XB4H AR30 XR30 AB30 XB30 AR24 AB24 XR24 XB24 AR15 RG16 R8   R16  GR88 GR32 YUV9 YU11 YU12 YU16 YU24 YVU9 YV11 YV12 YV16 YV24 NV12 P010 P012 P016 NV16 AYUV XYUV Y410 Y412 Y416 YUYV UYVY Y210 Y212 Y216
00:00:00.007 [render/egl.c:150] EGL DMA-BUF format modifiers unsupported
00:00:00.009 [render/gles2/renderer.c:870] Using OpenGL ES 3.2 Mesa 21.3.0-devel (git-73262d4bd4)
00:00:00.009 [render/gles2/renderer.c:871] GL vendor: AMD
00:00:00.009 [render/gles2/renderer.c:872] GL renderer: Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.10.52-1-MANJARO, LLVM 12.0.1)
00:00:00.009 [render/gles2/renderer.c:873] Supported GLES2 extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_filter_anisotropic GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_AMD_performance_monitor GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_NV_conditional_render GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_OES_viewport_array GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_robustness GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_group_vote GL_EXT_shader_implicit_conversions GL_EXT_shader_integer_mix GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_ANDROID_extension_pack_es31a GL_EXT_base_instance GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_copy_image GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_gpu_shader5 GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_render_snorm GL_EXT_shader_io_blocks GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_norm16 GL_EXT_texture_view GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_NV_image_formats GL_OES_copy_image GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_gpu_shader5 GL_OES_primitive_bounding_box GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_texture_view GL_EXT_blend_func_extended GL_EXT_buffer_storage GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_shader_samples_identical GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_OES_EGL_image_external_essl3 GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_shader_image_atomic GL_EXT_clip_cull_distance GL_EXT_disjoint_timer_query GL_EXT_texture_compression_s3tc_srgb GL_EXT_window_rectangles GL_MESA_shader_integer_functions GL_EXT_clip_control GL_EXT_color_buffer_half_float GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_texture_compression_bptc GL_KHR_parallel_shader_compile GL_NV_alpha_to_coverage_dither_control GL_AMD_framebuffer_multisample_advanced GL_EXT_EGL_image_storage GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_demote_to_helper_invocation GL_EXT_depth_clamp GL_EXT_texture_query_lod GL_MESA_bgra
00:00:00.013 [backend/noop/backend.c:59] Creating noop backend
00:00:00.013 [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
00:00:00.015 [../src/wlserver.cpp:580] Running compositor on wayland display 'gamescope-0'
00:00:00.015 [backend/headless/backend.c:27] Starting headless backend
00:00:00.016 [GLES2] Shader Stats: SGPRS: 24 VGPRS: 28 Code Size: 116 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.016 [GLES2] Shader Stats: SGPRS: 24 VGPRS: 8 Code Size: 164 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.016 [GLES2] Shader Stats: SGPRS: 24 VGPRS: 28 Code Size: 120 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.016 [GLES2] Shader Stats: SGPRS: 16 VGPRS: 8 Code Size: 144 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.016 [GLES2] Shader Stats: SGPRS: 8 VGPRS: 28 Code Size: 108 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.016 [GLES2] Shader Stats: SGPRS: 16 VGPRS: 12 Code Size: 180 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.016 [GLES2] Shader Stats: SGPRS: 8 VGPRS: 28 Code Size: 44 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.016 [GLES2] Shader Stats: SGPRS: 24 VGPRS: 28 Code Size: 116 LDS: 0 Scratch: 0 Max Waves: 8 Spilled SGPRs: 0 Spilled VGPRs: 0 PrivMem VGPRs: 0
00:00:00.017 [xwayland/server.c:99] WAYLAND_SOCKET=26 Xwayland :2 -rootless -terminate -core -listenfd 24 -listenfd 25 -wm -1
00:00:00.020 [backend/noop/backend.c:16] Starting noop backend
glamor: No eglstream capable devices found
[1231999.667] wl_display@1.get_registry(new id wl_registry@2)
[1231999.687]  -> wl_registry@2.global(1, "wl_shm", 1)
[1231999.702]  -> wl_registry@2.global(2, "wl_drm", 2)
[1231999.711]  -> wl_registry@2.global(3, "zwp_linux_dmabuf_v1", 3)
[1231999.721]  -> wl_registry@2.global(4, "wl_compositor", 4)
[1231999.732]  -> wl_registry@2.global(5, "wl_subcompositor", 1)
[1231999.743]  -> wl_registry@2.global(6, "gamescope_xwayland", 1)
[1231999.754]  -> wl_registry@2.global(7, "wl_seat", 7)
[1231999.765]  -> wl_registry@2.global(8, "wl_output", 3)
[1231999.776] wl_display@1.sync(new id wl_callback@3)
[1231999.783]  -> wl_callback@3.done(0)
[1231999.790]  -> wl_display@1.delete_id(3)
[1231999.849] wl_registry@2.bind(1, "wl_shm", 1, new id [unknown]@4)
[1231999.862]  -> wl_shm@4.format(0)
[1231999.868]  -> wl_shm@4.format(1)
[1231999.872]  -> wl_shm@4.format(875709016)
[1231999.876]  -> wl_shm@4.format(875708993)
[1231999.883] wl_registry@2.bind(2, "wl_drm", 2, new id [unknown]@5)
[1231999.898]  -> wl_drm@5.device("/dev/dri/renderD128")
[1231999.906]  -> wl_drm@5.format(808669761)
[1231999.915]  -> wl_drm@5.format(808669784)
[1231999.924]  -> wl_drm@5.format(808665665)
[1231999.935]  -> wl_drm@5.format(808665688)
[1231999.940]  -> wl_drm@5.format(875713089)
[1231999.946]  -> wl_drm@5.format(875713112)
[1231999.952]  -> wl_drm@5.format(909199186)
[1231999.958]  -> wl_drm@5.format(961959257)
[1231999.964]  -> wl_drm@5.format(825316697)
[1231999.969]  -> wl_drm@5.format(842093913)
[1231999.974]  -> wl_drm@5.format(909202777)
[1231999.980]  -> wl_drm@5.format(875713881)
[1231999.987]  -> wl_drm@5.format(842094158)
[1231999.993]  -> wl_drm@5.format(909203022)
[1231999.999]  -> wl_drm@5.format(1448695129)
[1232000.007]  -> wl_drm@5.capabilities(1)
[1232000.015] wl_registry@2.bind(3, "zwp_linux_dmabuf_v1", 3, new id [unknown]@6)
[1232000.040]  -> zwp_linux_dmabuf_v1@6.modifier(875713112, 16777215, 4294967295)
[1232000.054]  -> zwp_linux_dmabuf_v1@6.modifier(875713089, 16777215, 4294967295)
[1232000.065]  -> zwp_linux_dmabuf_v1@6.modifier(842094158, 16777215, 4294967295)
[1232000.080] wl_registry@2.bind(4, "wl_compositor", 4, new id [unknown]@7)
[1232000.097] wl_registry@2.bind(8, "wl_output", 2, new id [unknown]@8)
[1232000.130]  -> wl_output@8.geometry(0, 0, 0, 0, 0, "noop", "noop", 0)
[1232000.162]  -> wl_output@8.mode(1, 1280, 720, 60000)
[1232000.186]  -> wl_output@8.scale(1)
[1232000.193]  -> wl_output@8.done()
[1232000.201] wl_display@1.sync(new id wl_callback@3)
[1232000.211]  -> wl_callback@3.done(0)
[1232000.219]  -> wl_display@1.delete_id(3)
[1232014.710] wl_display@1.sync(new id wl_callback@3)
[1232014.745]  -> wl_callback@3.done(0)
[1232014.762]  -> wl_display@1.delete_id(3)
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86BrightnessAuto
> Warning:          Could not resolve keysym XF86DisplayOff
> Warning:          Could not resolve keysym XF86Info
> Warning:          Could not resolve keysym XF86AspectRatio
> Warning:          Could not resolve keysym XF86DVD
> Warning:          Could not resolve keysym XF86Audio
> Warning:          Could not resolve keysym XF86ChannelUp
> Warning:          Could not resolve keysym XF86ChannelDown
> Warning:          Could not resolve keysym XF86Break
> Warning:          Could not resolve keysym XF86VideoPhone
> Warning:          Could not resolve keysym XF86ZoomReset
> Warning:          Could not resolve keysym XF86Editor
> Warning:          Could not resolve keysym XF86GraphicsEditor
> Warning:          Could not resolve keysym XF86Presentation
> Warning:          Could not resolve keysym XF86Database
> Warning:          Could not resolve keysym XF86Voicemail
> Warning:          Could not resolve keysym XF86Addressbook
> Warning:          Could not resolve keysym XF86DisplayToggle
> Warning:          Could not resolve keysym XF86SpellCheck
> Warning:          Could not resolve keysym XF86ContextMenu
> Warning:          Could not resolve keysym XF86MediaRepeat
> Warning:          Could not resolve keysym XF8610ChannelsUp
> Warning:          Could not resolve keysym XF8610ChannelsDown
> Warning:          Could not resolve keysym XF86Images
> Warning:          Could not resolve keysym XF86NotificationCenter
> Warning:          Could not resolve keysym XF86PickupPhone
> Warning:          Could not resolve keysym XF86HangupPhone
> Warning:          Could not resolve keysym XF86Fn
> Warning:          Could not resolve keysym XF86Fn_Esc
> Warning:          Could not resolve keysym XF86FnRightShift
> Warning:          Could not resolve keysym XF86Numeric0
> Warning:          Could not resolve keysym XF86Numeric1
> Warning:          Could not resolve keysym XF86Numeric2
> Warning:          Could not resolve keysym XF86Numeric3
> Warning:          Could not resolve keysym XF86Numeric4
> Warning:          Could not resolve keysym XF86Numeric5
> Warning:          Could not resolve keysym XF86Numeric6
> Warning:          Could not resolve keysym XF86Numeric7
> Warning:          Could not resolve keysym XF86Numeric8
> Warning:          Could not resolve keysym XF86Numeric9
> Warning:          Could not resolve keysym XF86NumericStar
> Warning:          Could not resolve keysym XF86NumericPound
> Warning:          Could not resolve keysym XF86NumericA
> Warning:          Could not resolve keysym XF86NumericB
> Warning:          Could not resolve keysym XF86NumericC
> Warning:          Could not resolve keysym XF86NumericD
> Warning:          Could not resolve keysym XF86CameraFocus
> Warning:          Could not resolve keysym XF86WPSButton
> Warning:          Could not resolve keysym XF86CameraZoomIn
> Warning:          Could not resolve keysym XF86CameraZoomOut
> Warning:          Could not resolve keysym XF86CameraUp
> Warning:          Could not resolve keysym XF86CameraDown
> Warning:          Could not resolve keysym XF86CameraLeft
> Warning:          Could not resolve keysym XF86CameraRight
> Warning:          Could not resolve keysym XF86AttendantOn
> Warning:          Could not resolve keysym XF86AttendantOff
> Warning:          Could not resolve keysym XF86AttendantToggle
> Warning:          Could not resolve keysym XF86LightsToggle
> Warning:          Could not resolve keysym XF86ALSToggle
> Warning:          Could not resolve keysym XF86Buttonconfig
> Warning:          Could not resolve keysym XF86Taskmanager
> Warning:          Could not resolve keysym XF86Journal
> Warning:          Could not resolve keysym XF86ControlPanel
> Warning:          Could not resolve keysym XF86AppSelect
> Warning:          Could not resolve keysym XF86Screensaver
> Warning:          Could not resolve keysym XF86VoiceCommand
> Warning:          Could not resolve keysym XF86Assistant
> Warning:          Could not resolve keysym XF86BrightnessMin
> Warning:          Could not resolve keysym XF86BrightnessMax
> Warning:          Could not resolve keysym XF86KbdInputAssistPrev
> Warning:          Could not resolve keysym XF86KbdInputAssistNext
> Warning:          Could not resolve keysym XF86KbdInputAssistPrevgroup
> Warning:          Could not resolve keysym XF86KbdInputAssistNextgroup
> Warning:          Could not resolve keysym XF86KbdInputAssistAccept
> Warning:          Could not resolve keysym XF86KbdInputAssistCancel
> Warning:          Could not resolve keysym XF86RightUp
> Warning:          Could not resolve keysym XF86RightDown
> Warning:          Could not resolve keysym XF86LeftUp
> Warning:          Could not resolve keysym XF86LeftDown
> Warning:          Could not resolve keysym XF86RootMenu
> Warning:          Could not resolve keysym XF86MediaTopMenu
> Warning:          Could not resolve keysym XF86Numeric11
> Warning:          Could not resolve keysym XF86Numeric12
> Warning:          Could not resolve keysym XF86AudioDesc
> Warning:          Could not resolve keysym XF863DMode
> Warning:          Could not resolve keysym XF86NextFavorite
> Warning:          Could not resolve keysym XF86StopRecord
> Warning:          Could not resolve keysym XF86PauseRecord
> Warning:          Could not resolve keysym XF86VOD
> Warning:          Could not resolve keysym XF86Unmute
> Warning:          Could not resolve keysym XF86FastReverse
> Warning:          Could not resolve keysym XF86SlowReverse
> Warning:          Could not resolve keysym XF86Data
> Warning:          Could not resolve keysym XF86OnScreenKeyboard
> Warning:          Could not resolve keysym XF86PrivacyScreenToggle
> Warning:          Could not resolve keysym XF86SelectiveScreenshot
> Warning:          Could not resolve keysym XF86Macro1
> Warning:          Could not resolve keysym XF86Macro2
> Warning:          Could not resolve keysym XF86Macro3
> Warning:          Could not resolve keysym XF86Macro4
> Warning:          Could not resolve keysym XF86Macro5
> Warning:          Could not resolve keysym XF86Macro6
> Warning:          Could not resolve keysym XF86Macro7
> Warning:          Could not resolve keysym XF86Macro8
> Warning:          Could not resolve keysym XF86Macro9
> Warning:          Could not resolve keysym XF86Macro10
> Warning:          Could not resolve keysym XF86Macro11
> Warning:          Could not resolve keysym XF86Macro12
> Warning:          Could not resolve keysym XF86Macro13
> Warning:          Could not resolve keysym XF86Macro14
> Warning:          Could not resolve keysym XF86Macro15
> Warning:          Could not resolve keysym XF86Macro16
> Warning:          Could not resolve keysym XF86Macro17
> Warning:          Could not resolve keysym XF86Macro18
> Warning:          Could not resolve keysym XF86Macro19
> Warning:          Could not resolve keysym XF86Macro20
> Warning:          Could not resolve keysym XF86Macro21
> Warning:          Could not resolve keysym XF86Macro22
> Warning:          Could not resolve keysym XF86Macro23
> Warning:          Could not resolve keysym XF86Macro24
> Warning:          Could not resolve keysym XF86Macro25
> Warning:          Could not resolve keysym XF86Macro26
> Warning:          Could not resolve keysym XF86Macro27
> Warning:          Could not resolve keysym XF86Macro28
> Warning:          Could not resolve keysym XF86Macro29
> Warning:          Could not resolve keysym XF86Macro30
> Warning:          Could not resolve keysym XF86MacroRecordStart
> Warning:          Could not resolve keysym XF86MacroRecordStop
> Warning:          Could not resolve keysym XF86MacroPresetCycle
> Warning:          Could not resolve keysym XF86MacroPreset1
> Warning:          Could not resolve keysym XF86MacroPreset2
> Warning:          Could not resolve keysym XF86MacroPreset3
> Warning:          Could not resolve keysym XF86KbdLcdMenu1
> Warning:          Could not resolve keysym XF86KbdLcdMenu2
> Warning:          Could not resolve keysym XF86KbdLcdMenu3
> Warning:          Could not resolve keysym XF86KbdLcdMenu4
> Warning:          Could not resolve keysym XF86KbdLcdMenu5
Errors from xkbcomp are not fatal to the X server
[1232041.948] wl_shm@4.create_pool(new id wl_shm_pool@3, fd 33, 1024)
[1232041.976] wl_shm_pool@3.create_buffer(new id wl_buffer@9, 0, 16, 16, 64, 0)
[1232042.006] wl_shm_pool@3.destroy()
[1232042.011]  -> wl_display@1.delete_id(3)
[1232042.030] wl_display@1.get_registry(new id wl_registry@10)
[1232042.038]  -> wl_registry@10.global(1, "wl_shm", 1)
[1232042.049]  -> wl_registry@10.global(2, "wl_drm", 2)
[1232042.060]  -> wl_registry@10.global(3, "zwp_linux_dmabuf_v1", 3)
[1232042.070]  -> wl_registry@10.global(4, "wl_compositor", 4)
[1232042.092]  -> wl_registry@10.global(5, "wl_subcompositor", 1)
[1232042.113]  -> wl_registry@10.global(6, "gamescope_xwayland", 1)
[1232042.124]  -> wl_registry@10.global(7, "wl_seat", 7)
[1232042.134]  -> wl_registry@10.global(8, "wl_output", 3)
[1232042.153] wl_display@1.sync(new id wl_callback@11)
[1232042.159]  -> wl_callback@11.done(0)
[1232042.165]  -> wl_display@1.delete_id(11)
[1232042.259] wl_registry@2.bind(7, "wl_seat", 5, new id [unknown]@3)
[1232042.293]  -> wl_seat@3.name("seat0")
[1232042.310]  -> wl_seat@3.capabilities(7)
[1232042.316] wl_compositor@7.create_surface(new id wl_surface@12)
00:00:00.088 [types/wlr_surface.c:723] New wlr_surface 0x56410bb0b670 (res 0x56410bad3d50)
[1232042.352] wl_display@1.sync(new id wl_callback@11)
[1232042.359]  -> wl_callback@11.done(0)
[1232042.375]  -> wl_display@1.delete_id(11)
[1232042.612] wl_seat@3.get_pointer(new id wl_pointer@13)
[1232042.638] wl_pointer@13.set_cursor(0, nil, 0, 0)
[1232042.656] wl_seat@3.get_keyboard(new id wl_keyboard@14)
[1232042.787]  -> wl_keyboard@14.keymap(1, fd 34, 64354)
[1232042.803]  -> wl_keyboard@14.repeat_info(25, 600)
[1232042.819] wl_seat@3.get_touch(new id wl_touch@15)
00:00:00.090 [xwayland/server.c:259] Xserver is ready
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86BrightnessAuto
> Warning:          Could not resolve keysym XF86DisplayOff
> Warning:          Could not resolve keysym XF86Info
> Warning:          Could not resolve keysym XF86AspectRatio
> Warning:          Could not resolve keysym XF86DVD
> Warning:          Could not resolve keysym XF86Audio
> Warning:          Could not resolve keysym XF86ChannelUp
> Warning:          Could not resolve keysym XF86ChannelDown
> Warning:          Could not resolve keysym XF86Break
> Warning:          Could not resolve keysym XF86VideoPhone
> Warning:          Could not resolve keysym XF86ZoomReset
> Warning:          Could not resolve keysym XF86Editor
> Warning:          Could not resolve keysym XF86GraphicsEditor
> Warning:          Could not resolve keysym XF86Presentation
> Warning:          Could not resolve keysym XF86Database
> Warning:          Could not resolve keysym XF86Voicemail
> Warning:          Could not resolve keysym XF86Addressbook
> Warning:          Could not resolve keysym XF86DisplayToggle
> Warning:          Could not resolve keysym XF86SpellCheck
> Warning:          Could not resolve keysym XF86ContextMenu
> Warning:          Could not resolve keysym XF86MediaRepeat
> Warning:          Could not resolve keysym XF8610ChannelsUp
> Warning:          Could not resolve keysym XF8610ChannelsDown
> Warning:          Could not resolve keysym XF86Images
> Warning:          Could not resolve keysym XF86NotificationCenter
> Warning:          Could not resolve keysym XF86PickupPhone
> Warning:          Could not resolve keysym XF86HangupPhone
> Warning:          Could not resolve keysym XF86Fn
> Warning:          Could not resolve keysym XF86Fn_Esc
> Warning:          Could not resolve keysym XF86FnRightShift
> Warning:          Could not resolve keysym XF86Numeric0
> Warning:          Could not resolve keysym XF86Numeric1
> Warning:          Could not resolve keysym XF86Numeric2
> Warning:          Could not resolve keysym XF86Numeric3
> Warning:          Could not resolve keysym XF86Numeric4
> Warning:          Could not resolve keysym XF86Numeric5
> Warning:          Could not resolve keysym XF86Numeric6
> Warning:          Could not resolve keysym XF86Numeric7
> Warning:          Could not resolve keysym XF86Numeric8
> Warning:          Could not resolve keysym XF86Numeric9
> Warning:          Could not resolve keysym XF86NumericStar
> Warning:          Could not resolve keysym XF86NumericPound
> Warning:          Could not resolve keysym XF86NumericA
> Warning:          Could not resolve keysym XF86NumericB
> Warning:          Could not resolve keysym XF86NumericC
> Warning:          Could not resolve keysym XF86NumericD
> Warning:          Could not resolve keysym XF86CameraFocus
> Warning:          Could not resolve keysym XF86WPSButton
> Warning:          Could not resolve keysym XF86CameraZoomIn
> Warning:          Could not resolve keysym XF86CameraZoomOut
> Warning:          Could not resolve keysym XF86CameraUp
> Warning:          Could not resolve keysym XF86CameraDown
> Warning:          Could not resolve keysym XF86CameraLeft
> Warning:          Could not resolve keysym XF86CameraRight
> Warning:          Could not resolve keysym XF86AttendantOn
> Warning:          Could not resolve keysym XF86AttendantOff
> Warning:          Could not resolve keysym XF86AttendantToggle
> Warning:          Could not resolve keysym XF86LightsToggle
> Warning:          Could not resolve keysym XF86ALSToggle
> Warning:          Could not resolve keysym XF86Buttonconfig
> Warning:          Could not resolve keysym XF86Taskmanager
> Warning:          Could not resolve keysym XF86Journal
> Warning:          Could not resolve keysym XF86ControlPanel
> Warning:          Could not resolve keysym XF86AppSelect
> Warning:          Could not resolve keysym XF86Screensaver
> Warning:          Could not resolve keysym XF86VoiceCommand
> Warning:          Could not resolve keysym XF86Assistant
> Warning:          Could not resolve keysym XF86BrightnessMin
> Warning:          Could not resolve keysym XF86BrightnessMax
> Warning:          Could not resolve keysym XF86KbdInputAssistPrev
> Warning:          Could not resolve keysym XF86KbdInputAssistNext
> Warning:          Could not resolve keysym XF86KbdInputAssistPrevgroup
> Warning:          Could not resolve keysym XF86KbdInputAssistNextgroup
> Warning:          Could not resolve keysym XF86KbdInputAssistAccept
> Warning:          Could not resolve keysym XF86KbdInputAssistCancel
> Warning:          Could not resolve keysym XF86RightUp
> Warning:          Could not resolve keysym XF86RightDown
> Warning:          Could not resolve keysym XF86LeftUp
> Warning:          Could not resolve keysym XF86LeftDown
> Warning:          Could not resolve keysym XF86RootMenu
> Warning:          Could not resolve keysym XF86MediaTopMenu
> Warning:          Could not resolve keysym XF86Numeric11
> Warning:          Could not resolve keysym XF86Numeric12
> Warning:          Could not resolve keysym XF86AudioDesc
> Warning:          Could not resolve keysym XF863DMode
> Warning:          Could not resolve keysym XF86NextFavorite
> Warning:          Could not resolve keysym XF86StopRecord
> Warning:          Could not resolve keysym XF86PauseRecord
> Warning:          Could not resolve keysym XF86VOD
> Warning:          Could not resolve keysym XF86Unmute
> Warning:          Could not resolve keysym XF86FastReverse
> Warning:          Could not resolve keysym XF86SlowReverse
> Warning:          Could not resolve keysym XF86Data
> Warning:          Could not resolve keysym XF86OnScreenKeyboard
> Warning:          Could not resolve keysym XF86PrivacyScreenToggle
> Warning:          Could not resolve keysym XF86SelectiveScreenshot
> Warning:          Could not resolve keysym XF86Macro1
> Warning:          Could not resolve keysym XF86Macro2
> Warning:          Could not resolve keysym XF86Macro3
> Warning:          Could not resolve keysym XF86Macro4
> Warning:          Could not resolve keysym XF86Macro5
> Warning:          Could not resolve keysym XF86Macro6
> Warning:          Could not resolve keysym XF86Macro7
> Warning:          Could not resolve keysym XF86Macro8
> Warning:          Could not resolve keysym XF86Macro9
> Warning:          Could not resolve keysym XF86Macro10
> Warning:          Could not resolve keysym XF86Macro11
> Warning:          Could not resolve keysym XF86Macro12
> Warning:          Could not resolve keysym XF86Macro13
> Warning:          Could not resolve keysym XF86Macro14
> Warning:          Could not resolve keysym XF86Macro15
> Warning:          Could not resolve keysym XF86Macro16
> Warning:          Could not resolve keysym XF86Macro17
> Warning:          Could not resolve keysym XF86Macro18
> Warning:          Could not resolve keysym XF86Macro19
> Warning:          Could not resolve keysym XF86Macro20
> Warning:          Could not resolve keysym XF86Macro21
> Warning:          Could not resolve keysym XF86Macro22
> Warning:          Could not resolve keysym XF86Macro23
> Warning:          Could not resolve keysym XF86Macro24
> Warning:          Could not resolve keysym XF86Macro25
> Warning:          Could not resolve keysym XF86Macro26
> Warning:          Could not resolve keysym XF86Macro27
> Warning:          Could not resolve keysym XF86Macro28
> Warning:          Could not resolve keysym XF86Macro29
> Warning:          Could not resolve keysym XF86Macro30
> Warning:          Could not resolve keysym XF86MacroRecordStart
> Warning:          Could not resolve keysym XF86MacroRecordStop
> Warning:          Could not resolve keysym XF86MacroPresetCycle
> Warning:          Could not resolve keysym XF86MacroPreset1
> Warning:          Could not resolve keysym XF86MacroPreset2
> Warning:          Could not resolve keysym XF86MacroPreset3
> Warning:          Could not resolve keysym XF86KbdLcdMenu1
> Warning:          Could not resolve keysym XF86KbdLcdMenu2
> Warning:          Could not resolve keysym XF86KbdLcdMenu3
> Warning:          Could not resolve keysym XF86KbdLcdMenu4
> Warning:          Could not resolve keysym XF86KbdLcdMenu5
Errors from xkbcomp are not fatal to the X server
[1232084.105] wl_compositor@7.create_surface(new id wl_surface@11)
00:00:00.130 [types/wlr_surface.c:723] New wlr_surface 0x56410bb27960 (res 0x56410bb02a10)
[1232092.481] zwp_linux_dmabuf_v1@6.create_params(new id zwp_linux_buffer_params_v1@16)
[1232092.526] zwp_linux_buffer_params_v1@16.add(fd 37, 0, 0, 1216, 16777215, 4294967295)
[1232092.556] zwp_linux_buffer_params_v1@16.create_immed(new id wl_buffer@17, 300, 300, 875713112, 0)
[1232092.615] zwp_linux_buffer_params_v1@16.destroy()
[1232092.634]  -> wl_display@1.delete_id(16)
[1232092.660] wl_surface@11.attach(wl_buffer@17, 0, 0)
[1232092.698] wl_surface@11.damage_buffer(0, 0, 300, 300)
[1232092.744] wl_surface@11.frame(new id wl_callback@18)
[1232092.755] wl_surface@11.commit()
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
[1232106.878] zwp_linux_dmabuf_v1@6.create_params(new id zwp_linux_buffer_params_v1@19)
[1232106.928] zwp_linux_buffer_params_v1@19.add(fd 38, 0, 0, 2048, 16777215, 4294967295)
[1232106.959] zwp_linux_buffer_params_v1@19.create_immed(new id wl_buffer@20, 300, 300, 875713112, 0)
[1232106.997] zwp_linux_buffer_params_v1@19.destroy()
[1232107.007]  -> wl_display@1.delete_id(19)
[1232107.018] wl_surface@11.attach(wl_buffer@20, 0, 0)
[1232107.029] wl_surface@11.damage_buffer(0, 0, 300, 300)
[1232107.051] wl_surface@11.commit()
[1232107.072]  -> wl_buffer@17.release()
[1232107.325]  -> wl_pointer@13.enter(1, wl_surface@11, 150.000000, 150.000000)
[1232107.354]  -> wl_pointer@13.frame()
[1232107.363]  -> wl_keyboard@14.enter(2, wl_surface@11, array)
[1232107.377]  -> wl_keyboard@14.modifiers(3, 0, 0, 0, 0)
[1232107.483] wl_pointer@13.set_cursor(1, nil, 0, 0)
gamescope: ../src/steamcompmgr.cpp:599: bool import_commit(wlr_buffer*, wlr_dmabuf_attributes*, commit_t&): Assertion `commit.vulkanTex != 0' failed.
(EE) failed to write to XWayland fd: Broken pipe
Aborted (core dumped)
```

</details>

## System Info

```
 ██████████████████  ████████     ████@████
 ██████████████████  ████████     OS: Manjaro 21.1.0 Pahvo
 ██████████████████  ████████     Kernel: x86_64 Linux 5.10.52-1-MANJARO
 ██████████████████  ████████     Uptime: 20m
 ████████            ████████     Packages: 1682
 ████████  ████████  ████████     Shell: bash 5.1.8
 ████████  ████████  ████████     Resolution: 3120x1920
 ████████  ████████  ████████     DE: KDE 5.84.0 / Plasma 5.22.3
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme:  [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breeze
 ████████  ████████  ████████     Disk: 1.3T / 3.8T (34%)
 ████████  ████████  ████████     CPU: Intel Core i7-4770K @ 8x 3.9GHz [43.0°C]
 ████████  ████████  ████████     GPU: Radeon RX 590 Series (POLARIS10, DRM 3.40.0, 5.10.52-1-MANJARO, LLVM 12.0.1)
                                  RAM: 3407MiB / 11912MiB
```

Some notes:
- Tried with both `stable` and `git` versions of mesa packages, both failed.
- Kept it simple with glxgears, which works when not trying to run through gamescope.
- I've tried running vkcube outside of gamescope and noticed that it would close immediately with no errors logged.

So, it could perhaps be an issue on Polaris based cards -- though I haven't had any issues with dxvk or other vulkan programs prior to trying gamescope.

**Comment by Eoin-ONeill-Yokai** [comment]
Ah, digging into this more, I found that the `CVulkanTexture:BInit` function was missing a error log in one of the failure conditions. Adding

```patch
diff --git a/src/rendervulkan.cpp b/src/rendervulkan.cpp
index 9fa26fc..586d6c9 100644
--- a/src/rendervulkan.cpp
+++ b/src/rendervulkan.cpp
@@ -508,6 +508,7 @@ bool CVulkanTexture::BInit( uint32_t width, uint32_t height, VkFormat format, cr
        }

        if (vkAllocateMemory(device, &allocInfo, nullptr, &m_vkImageMemory) != VK_SUCCESS) {
+               fprintf( stderr, "vkAllocateMemory failed\n" );
                return false;
        }

``` 

Let me see that allocating memory has failed. I might dig into this more on my system...

**Comment by ademlabs** [comment]
I think I'm having the same issue as well. Using an RX580 on EndeavorOS (Arch), Kernel 5.13.9, Mesa 21.1.6.1

```
vkAllocateMemory failed
gamescope: ../gamescope/src/steamcompmgr.cpp:599: bool import_commit(wlr_buffer*, wlr_dmabuf_attributes*, commit_t&): Assertion `commit.vulkanTex != 0' failed.
(EE) failed to write to XWayland fd: Broken pipe
X connection to :2 broken (explicit kill or server shutdown).
```

[Crash log file](https://github.com/Plagman/gamescope/files/6978431/crash.log) attached.

**Comment by ronoverdrive** [comment]
I think I'm having the same issue, getting the same error as @ademlabs when I attempt to use gamescope. Arch Linux, Kernel 5.13.11-TkG CacULE, MESA 21.3.0-devel (git-dab97fe227), RX 5600XT.

**Comment by Eoin-ONeill-Yokai** [comment]
I no longer have this issue since reinstallation.

My best guess is that somewhere I had leftover AMDGPU Pro vulkan driver libraries that were causing invalid vulkan calls. If you're someone who has installed any AMDGPU Pro libraries in the past (in my case, it was for OpenCL use), make sure that those drivers aren't installed, along with their additional modules and test again.

**Comment by MGThePro** [comment]
I have updated gamescope to the latest version and seems to work for me as well now, without a reinstall or touching any amdgpu pro drivers

**Comment by tzcrawford** [comment]
> I have updated gamescope to the latest version and seems to work for me as well now, without a reinstall or touching any amdgpu pro drivers
 
It wasn't working for me initially with regular updates but I re-installed some of the graphics packages and now it appears to be working... Not sure, but may have been related to vdpau/libva because I seem to remember some system update made me uninstall that at some point and I never reinstalled. Now if I uninstall vdpau/libva packages it still works. Not sure.

This is what my setup looks like at this point:
```
gamescope 3.8.4-1
linux-zen 5.13.10.zen1-1
vulkan-radeon 21.1.6-1
lib32-vulkan-radeon 21.1.6-1
mesa 21.1.6-1
lib32-mesa 21.1.6-1
xf86-video-amdgpu 21.0.0-1
libva-mesa-driver 21.1.6-1
lib32-libva-mesa-driver 21.1.6-1
mesa-vdpau 21.1.6-1
lib32-mesa-vdpau 21.1.6-1
xorg-server 1.20.13-2
```

**Comment by f1nbar** [comment]
Having the same issue (AMD RX480 and R5 3600) running glxgears: 
```gamescope: ../src/steamcompmgr.cpp:599: bool import_commit(wlr_buffer*, wlr_dmabuf_attributes*, commit_t&): Assertion `commit.vulkanTex != 0' failed.```

**Comment by timlag1305** [comment]
I fixed this issue by uninstalling amdvlk and installing vulkan-radeon on arch linux.

**Comment by ronoverdrive** [comment]
ok yep, uninstalled amdvlk and it started working. Kinda odd that even when using the VK_ICD_FILENAMES to define radeon_icd instead of amd it would still crash. Really a shame because there's some things that either don't perform as well or won't work without amdvlk like AMF support in OBS for recording.

**Comment by ademlabs** [comment]
You can also install vulkan-radeon alongside amdvlk and run gamescope with the following by specifying which vulkan driver to use:
`AMD_VULKAN_ICD=RADV gamescope glxgears`

**Comment by ronoverdrive** [comment]
> You can also install vulkan-radeon alongside amdvlk and run gamescope with the following by specifying which vulkan driver to use:
> `AMD_VULKAN_ICD=RADV gamescope glxgears`

VK_ICD_FILENAMES does the same thing as AMD_VULKAN_ICD except you're defining the exact json files. Defining it to use RADV instead of AMDVLK still results in a crash with gamescope for me unless I completely remove AMDVLK.

**Comment by Birbelym** [comment]
> I fixed this issue by uninstalling amdvlk and installing vulkan-radeon on arch linux.

This was my issue as well, except it was `xf86-video-amdgpu`.

**Comment by solarfl4re** [comment]
On my Arch system uninstalling `lib32-amdvlk` fixed the problem. I had removed amdvlk and installed vulkan-radeon, but forgot about `lib32`.
