### ISSUE TITLE
Some games incorrectly recognize the mouse buttons

### ISSUE THREAD

**Issue by KayKay91** [Plagman/gamescope#234]
I own a Logitech G102 Lightsync mouse which has two more additional buttons which are placed at the left side and are mapped as MOUSE4 and MOUSE5 in each game that supports it. However, when running some games in Gamescope they register them as MOUSE6 and 7 instead and considering that having 5 mouse buttons is a "norm" in current times, they cannot be binded at all.

This happens in the following games i own:
- Doom Eternal
- Quake Champions
- GZDoom* (Source port of Doom)
- Quakespasm Spiked (Source port of Quake 1)
- Doom 64
- Team Fortress 2 **
- Magrunner: Dark Pulse
*- The software incorrectly recognizes the buttons but can bind em
**- The software recognizes the buttons correctly and can bind em.

Appearently majority of the time it happens with games that are running in Proton/Wine, but in native linux games they are incorrectly mapped or just recognizes the proper buttons.

**Comment by lord-re** [comment]
> Interesting. My mouse buttons aren't even recognized. I press button 4 or 5 and it doesn't even register the button push. I have a G502 Hero.

Same with a steelseries rival 600.

**Comment by hasezoey** [comment]
for me and my mouse (Logitech G502 Wireless (via powerplay)) it is the same as original issue: MOUSE4 and MOUSE5 are recognized as MOUSE6 and MOUSE7 (i tried Sword Art Online: Fatal Bullet via Proton, where everything above MOUSE5 does not register at all, and Factorio (native) where it registers as MOUSE6 and MOUSE7)

note: if it matters, i use KDE Plasma (wayland) with keyboard map "de" (German)

**Comment by IDeathByte** [comment]
Same. Buttons not recognized in Arma 3
Plasma wayland
Logitech M570 and controller mapping emulation through steam

**Comment by hjri** [comment]
same issue with Zowie ZA11 and Titan Quest.

Running GZDoom with gamescope shows that buttons 4 and 5 are recognized as MOUSE6 and MOUSE7 (which aren't exactly standard) while running GZDoom without those buttons are MOUSE4 and MOUSE5 respectively. I assume that most games just don't recognize mouse buttons 6 and beyond, since I think those aren't supported on windows to begin with.

**Comment by Doomsdayrs** [comment]
Logitech G502, WarThunder

Typically I use the side buttons for elevation  + / - . Makes the game nearly unplayable for my standard of game play.

**Comment by emersion** [comment]
Fixed in #433

**Comment by Figuera** [comment]
I did fix the problem in my case. Thank you.

**Comment by daynashaw** [comment]
Hello!

Unfortunately I am still experiencing this bug. I am using the Logitech Pro Superlight. I am running Fedora Silverblue 35. 

I have tested in Planetside 2
gamescope -h 1080 -H 1440 -U -f -- mangohud gamemoderun %command% --disable-gpu

Battlefield 4
gamescope -h 1080 -H 1440 -U -f -- mangohud gamemoderun %command%

and Apex Legends
gamescope -h 1080 -H 1440 -U -f -- mangohud gamemoderun %command%

In all three of these games the mouse buttons 4 and 5 are not forwarded to the game. When attempting to set the binds in these games by pressing the relevant mouse buttons there is no response from the game.

Thanks!

**Comment by daynashaw** [comment]
Can this issue be reopened?

**Comment by massatt212** [comment]
my mouse goes crazy fast going left and right and wont go up and down untless i have steamos compositor running in the background, mouse wont work if i run gamescope alone in steamos compositor
